/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-02-07 05:13:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    span{width: 150px; color: red;}\r\n");
      out.write("    input{border: 1px solid red;}\r\n");
      out.write("    table{width: 100% ;}\r\n");
      out.write("    table th,td{border: 1px solid gray; text-align: center;}\r\n");
      out.write("    h2 { text-align: center}\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2> 회원 정보 입력하기 </h2>\r\n");
      out.write("    <form name=\"myform\" method=\"post\" id=\"myform\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr bgcolor=\"pink\">\r\n");
      out.write("                    <th>아이디</th>\r\n");
      out.write("                    <th>비밀번호</th>\r\n");
      out.write("                    <th>이름</th>\r\n");
      out.write("                    <th>이메일</th>\r\n");
      out.write("                    <th>전화번호</th>\r\n");
      out.write("                    <th>관리자</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><input type=\"text\" size=\"14\" name=\"userid\" id=\"userid\" />\r\n");
      out.write("                        <span>중복결과여부</span>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td><input type=\"password\" size=\"14\" name=\"pwd\" id=\"pwd\" /></td>\r\n");
      out.write("                    <td><input type=\"text\" size=\"14\" name=\"usernm\" id=\"usernm\" /></td>\r\n");
      out.write("                    <td><input type=\"email\" size=\"14\" name=\"email\" id=\"email\" /></td>\r\n");
      out.write("                    <td><input type=\"text\" size=\"14\" name=\"phone\" id=\"phone\" /></td>\r\n");
      out.write("                    <td><input type=\"text\" size=\"14\" name=\"admin\" id=\"admin\" /></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("            <tfoot>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"6\" align=\"center\">\r\n");
      out.write("                        <input type=\"button\" value=\"가입하기\" id=\"btn\" />  \r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tfoot>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    <br /><br /><br /><br /><br />\r\n");
      out.write("    <h2> 멤버 리스트 </h2>\r\n");
      out.write("    <div>\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr bgcolor=\"skyblue\">\r\n");
      out.write("                    <th>ID</th><th>PASSWORD</th><th>NAME</th>\r\n");
      out.write("                    <th>EMAIL</th><th>PHONE</th><th>DELETE</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody id=\"tbody\">\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        function getList() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url : \"/memberList\",\r\n");
      out.write("                type : \"get\",\r\n");
      out.write("                success : function(data) {\r\n");
      out.write("                   \tconsole.info(\"data.length : \"+data.length);\r\n");
      out.write("                   \tvar table = \"\";\r\n");
      out.write("                    for(var str in data){\r\n");
      out.write("                    \ttable +=\"<tr>\";\r\n");
      out.write("                        table +=\"<td>\"+data[str]['userid']+\"</td>\";\r\n");
      out.write("                        table +=\"<td>\"+data[str]['pwd']+\"</td>\";\r\n");
      out.write("                        table +=\"<td>\"+data[str]['usernm']+\"</td>\";\r\n");
      out.write("                        table +=\"<td>\"+data[str]['email']+\"</td>\";\r\n");
      out.write("                        table +=\"<td>\"+data[str]['phone']+\"</td>\";\r\n");
      out.write("                        table +=\"<td>\" ;\r\n");
      out.write("                        table += \"<input type='button' value='삭제' id='del' name='\"+data[str]['userid']+\"' />\";\r\n");
      out.write("                        table +=\"</tr>\";\r\n");
      out.write("                    }\r\n");
      out.write("                    $(\"#tbody\").append(table);   \r\n");
      out.write("                },\r\n");
      out.write("                error : function(error) {\r\n");
      out.write("                    alert(\"실패\"+error);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }// getList()끝\r\n");
      out.write("        \r\n");
      out.write("        // 중복확인\r\n");
      out.write("        $(\"#userid\").keyup(function() {\r\n");
      out.write("        \t\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url : \"/memberIdChk\",\r\n");
      out.write("                type : \"get\",\r\n");
      out.write("                dataType : \"text\",\r\n");
      out.write("                data : \"userid=\"+$(\"#userid\").val(), // 서블릿으로 넘어가는 파라미터값\r\n");
      out.write("                success : function(data) {\r\n");
      out.write("                    $(\"span\").html(data);\r\n");
      out.write("                },\r\n");
      out.write("                error : function name() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });// 중복확인\r\n");
      out.write("        \r\n");
      out.write("        // 회원가입\r\n");
      out.write("        $(\"#btn\").click(function() {\r\n");
      out.write("        \tvar data = $(\"#myform\").serialize();\r\n");
      out.write("        \tconsole.info(\"data : \"+data);\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url : \"/memberInsert\",\r\n");
      out.write("                type : \"post\",\r\n");
      out.write("                dataType : \"text\",\r\n");
      out.write("                data : data, // 파라미터를 직렬화\r\n");
      out.write("                success : function(data) {\r\n");
      out.write("                    if(data == 1){\r\n");
      out.write("                        alert(\"회원가입성공\");\r\n");
      out.write("                        $(\"#tbody\").empty();\r\n");
      out.write("                        getList();\r\n");
      out.write("                        $(\"tbody input[type]\").each(function() {\r\n");
      out.write("                            $(this).val(\"\");\r\n");
      out.write("                        })\r\n");
      out.write("                        \r\n");
      out.write("                    }else{\r\n");
      out.write("                        alert(\"회원가입실패\");    \r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error : function name() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }); // 회원가입 끝\r\n");
      out.write("        \r\n");
      out.write("        // 삭제\r\n");
      out.write("        $(\"table\").on(\"click\",\"#del\",function(){\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url : \"/memberDelete\",\r\n");
      out.write("                type : \"post\",\r\n");
      out.write("                dataType : \"text\",\r\n");
      out.write("                data : \"userid=\"+$(this).attr(\"name\"), // 파라미터를 직렬화\r\n");
      out.write("                success : function(data) {\r\n");
      out.write("                    if(data == 1){\r\n");
      out.write("                        alert(\"삭제성공\");\r\n");
      out.write("                        $(\"#tbody\").empty();\r\n");
      out.write("                        getList();\r\n");
      out.write("                    }else{\r\n");
      out.write("                        alert(\"삭제실패\");\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error : function name() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        // 리스트 함수 실행\r\n");
      out.write("        getList();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
